### ISSUE TITLE
 Help me step motor but it goes like this. 

### ISSUE THREAD

**Issue by choiiot** [blynkkk/blynk-sketch-generator#100]
In file included from C:\Users\choi-\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:17:0,
                 from C:\Users\choi-\Documents\Arduino\libraries\Blynk\src/BlynkApiArduino.h:14,
                 from C:\Users\choi-\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp8266.h:24,
                 from C:\Users\choi-\Documents\Arduino\step\IoT CNC Shield, Nodemcu CNC shield, ESP8266 CNC Shield, Mobile CNC Shield 210124\cnc_shield_step_motor_nodemcu_esp8266\cnc_shield_step_motor_nodemcu_esp8266.ino:12:
C:\Users\choi-\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkTimer.h:36:21: error: redefinition of 'class BlynkTimer'
 #define SimpleTimer BlynkTimer
                     ^
C:\Users\choi-\Documents\Arduino\libraries\SimpleTimer/SimpleTimer.h:10:7: note: in expansion of macro 'SimpleTimer'
 class SimpleTimer {
       ^
C:\Users\choi-\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkTimer.h:36:21: error: previous definition of 'class BlynkTimer'
 #define SimpleTimer BlynkTimer
                     ^
C:\Users\choi-\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkTimer.h:41:7: note: in expansion of macro 'SimpleTimer'
 class SimpleTimer {
       ^
exit status 1
board NodeMCU 1.0 (ESP-12E Module) 
Compilation error

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc/
