### ISSUE TITLE
interrupt not happening

### ISSUE THREAD

**Issue by saif177** [blynkkk/blynk-sketch-generator#101]
i am working on a project with nodeMCU32 and i been trying from couple of days to get interrupt work but no luck . idk why the far i reached is turning on/off led but no luck with any value change for variable or print message on serial monitor. please help me with it.  here is my code from Blynk Example codes ->
https://examples.blynk.cc/?board=NodeMCU&shield=ESP8266%20WiFi&example=More%2FSync%2FButtonInterrupt

i am using ESP32 WROOM-32

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc

Most probably you should select ESP32 for NodeMCU32
