### ISSUE TITLE
All examples for Particle Photon using attachInterrupt will crash

### ISSUE THREAD

**Issue by jenschr** [blynkkk/blynk-sketch-generator#102]
Kind of depressing letting my students use Blynk with Particle Photon. All examples that use attachInterrupt will fail - ref this forum post from 2015: https://community.blynk.cc/t/email-and-push-notifications-on-particle-photon/2601/3 (yes- the issue still exist. nobody fixed it.

Also as mentioned "digitalPinToInterrupt" does not exist in Particle's API. This is a concious omission in their case since Particle will do this for you autmatically instead, but it should be corrected in the samplecode. 

Here is my suggested replacement for the Push Notification example that solves the above two issues: https://go.particle.io/shared_apps/605ba437de63ee0009f529e0

URL to the faulty code:
https://examples.blynk.cc/?board=Particle%20Photon&shield=Particle%20WiFi&example=Widgets%2FPushNotification%2FPushNotification_Button

**Comment by doom369** [comment]
@vshymanskyy please take a look

**Comment by vshymanskyy** [comment]
We cannot guarantee that all combinations of all boards/shields/3rd party library versions will work.
These are just examples.

**Comment by jenschr** [comment]
@vshymanskyy So instead of making that simple fix, you'll rather want bad rep for your product? Ok.... I guess? (But it does not make me or others eager to report any other issues)

**Comment by vshymanskyy** [comment]
it's not a simple fix. unfortunately such a "fix"  would break this example for all other platforms/boards.
the only thing i can do easily is to remove the example completely.

**Comment by vshymanskyy** [comment]
Done. This is removed now, the example will disappear with the next update

**Comment by jenschr** [comment]
I am sorry. I must have misunderstood something here. These examples did all use to be platform specific? If I change things in the menu here https://examples.blynk.cc/?board=Particle%20Photon&shield=Particle%20WiFi&example=Widgets%2FPushNotification%2FPushNotification_Button it will show a different example for "Push Notification Button" for every board. They are unique to each board?

So since they are distinct and per platform, all you'd need to do was to remove "digitalPinToInterrupt" and just hardcode the interrupt to for example D7.

https://docs.particle.io/reference/device-os/api/interrupts/attachinterrupt/

**Comment by vshymanskyy** [comment]
No, these examples are generated from templates. We don't have a separate
example for each of the thousands of different platform/shield/example
combinations...

**Comment by jenschr** [comment]
Oh. Quite a few of them have instructions that deviate from the base example, so that was not obvious. I fully agree with your solution then. Better not have it there if it crashes and it's not possible to customize for each platform.
