### ISSUE TITLE
Example has error

### ISSUE THREAD

**Issue by Code-With-Marley** [blynkkk/blynk-sketch-generator#108]
Hi, Marley Here! I have a problem.
When I run this Example:
`
/*************************************************************
  

  This is a simple demo of sending and receiving some data.
  Be sure to check out other examples!
 *************************************************************/

// Template ID, Device Name and Auth Token are provided by the Blynk.Cloud
// See the Device Info tab, or Template settings
#define BLYNK_TEMPLATE_ID           "TMPL0kj8IoDd"
#define BLYNK_DEVICE_NAME           "Quickstart Device"
#define BLYNK_AUTH_TOKEN            "1U4mHmY2RLSDQNJONucQR_9T1_NJj5eN"

// Comment this out to disable prints and save space
#define BLYNK_PRINT SwSerial

#include <SoftwareSerial.h>
SoftwareSerial SwSerial(10, 11); // RX, TX

#include <BlynkSimpleStream.h>

char auth[] = BLYNK_AUTH_TOKEN;

BlynkTimer timer;

// This function is called every time the Virtual Pin 0 state changes
BLYNK_WRITE(V0)
{
  // Set incoming value from pin V0 to a variable
  int value = param.asInt();

  // Update state
  Blynk.virtualWrite(V1, value);
}

// This function is called every time the device is connected to the Blynk.Cloud
BLYNK_CONNECTED()
{
  // Change Web Link Button message to "Congratulations!"
  Blynk.setProperty(V3, "offImageUrl", "https://static-image.nyc3.cdn.digitaloceanspaces.com/general/fte/congratulations.png");
  Blynk.setProperty(V3, "onImageUrl",  "https://static-image.nyc3.cdn.digitaloceanspaces.com/general/fte/congratulations_pressed.png");
  Blynk.setProperty(V3, "url", "https://docs.blynk.io/en/getting-started/what-do-i-need-to-blynk/how-quickstart-device-was-made");
}

// This function sends Arduino's uptime every second to Virtual Pin 2.
void myTimerEvent()
{
  // You can send any value at any time.
  // Please don't send more that 10 values per second.
  Blynk.virtualWrite(V2, millis() / 1000);
}

void setup()
{
  // Debug console
  SwSerial.begin(115200);

  // Blynk will work through Serial
  // Do not read or write this serial manually in your sketch
  Serial.begin(9600);
  Blynk.begin(Serial, auth);

  // Setup a function to be called every second
  timer.setInterval(1000L, myTimerEvent);
}

void loop()
{
  Blynk.run();
  timer.run();
  // You can inject your own code or combine it with other sketches.
  // Check other examples on how to communicate with Blynk. Remember
  // to avoid delay() function!
}
`

I get an error:
`
Arduino: 1.8.13 (Mac OS X), Board: "Arduino Uno"

In file included from /Users/******/sketchbook/libraries/Blynk/src/Blynk/BlynkApi.h:38:0,
                 from /Users/******/sketchbook/libraries/Blynk/src/BlynkApiArduino.h:14,
                 from /Users/******/sketchbook/libraries/Blynk/src/Adapters/BlynkSerial.h:18,
                 from /Users/******/sketchbook/libraries/Blynk/src/BlynkSimpleStream.h:18,
                 from /var/folders/c_/j1yzzwwd36sfttn9tz70r9340000gq/T/arduino_modified_sketch_429917/sketch_oct08a.ino:22:
/Users/******/sketchbook/libraries/Blynk/src/Blynk/BlynkConsole.h:20:10: fatal error: functional: No such file or directory
 #include <functional>
          ^~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by vshymanskyy** [comment]
It was fixed long time ago
