### ISSUE TITLE
blynk esp8266 wifi

### ISSUE THREAD

**Issue by Snippen59** [blynkkk/blynk-sketch-generator#114]
Hi.

I can`t ad anything in the sketch. In this case, yournetworkname and password.

Regards

n. kr. roren

**Comment by Wahyudin1606** [comment]
have searched and read many others with this problem but cannot seem to fix my problem.

So in the app I selected for a new token and received an email with:
Auth Token : "qHFNWBFyS1ulRRhUyChQzzlgu4l2emQW"

**Comment by vshymanskyy** [comment]
Please use community.blynk.cc/
