### ISSUE TITLE
Sketch for Arduino Uno and Ethernet shield - connection to Blynk server fails.

### ISSUE THREAD

**Issue by ebjowei** [blynkkk/blynk-sketch-generator#115]
Hi,
I use Blynk Example Browser to create sketch for Arduino Uno with Ethernet shield v2. I also tried new automatically created template for my setup. Connection to Blynk server does not work and I suspect problem is on device side. 
My setup is:
Arduino Uno rev 3 with Ethernet shield 2 (W5500 chip) connected.
The code generated by Example Browser can be found below. I also attached screen shots of the serial terminal monitor. Seems that connection is not successful. I tried to change includes to Ethernet.h instead of Ethernet2.h and BlynkSimpleEthernet.h instead of BlynkSimpleEthernet2.h. Then I do get a ping but periodic reconnections "forever". 

I am positive that the internet connection itself is ok, that is also supported by the fact that Blynk server can be pinged. But it seems that for some reason connection is dropped.

Best regards Björn

/*************************************************************

  This is a simple demo of sending and receiving some data.
  Be sure to check out other examples!
 *************************************************************/

// Template ID, Device Name and Auth Token are provided by the Blynk.Cloud
// See the Device Info tab, or Template settings
#define BLYNK_TEMPLATE_ID           "TMPLixABkY67"
#define BLYNK_DEVICE_NAME           "Quickstart Template"
#define BLYNK_AUTH_TOKEN            "n1FOQhcYoxKypVJdzpbC3G3nZoT_Mb-T"

// Comment this out to disable prints and save space
#define BLYNK_PRINT Serial

#include <SPI.h>
#include <Ethernet2.h>
#include <BlynkSimpleEthernet2.h>

char auth[] = BLYNK_AUTH_TOKEN;

BlynkTimer timer;

// This function is called every time the Virtual Pin 0 state changes
BLYNK_WRITE(V0)
{
  // Set incoming value from pin V0 to a variable
  int value = param.asInt();

  // Update state
  Blynk.virtualWrite(V1, value);
}

// This function is called every time the device is connected to the Blynk.Cloud
BLYNK_CONNECTED()
{
  // Change Web Link Button message to "Congratulations!"
  Blynk.setProperty(V3, "offImageUrl", "https://static-image.nyc3.cdn.digitaloceanspaces.com/general/fte/congratulations.png");
  Blynk.setProperty(V3, "onImageUrl",  "https://static-image.nyc3.cdn.digitaloceanspaces.com/general/fte/congratulations_pressed.png");
  Blynk.setProperty(V3, "url", "https://docs.blynk.io/en/getting-started/what-do-i-need-to-blynk/how-quickstart-device-was-made");
}

// This function sends Arduino's uptime every second to Virtual Pin 2.
void myTimerEvent()
{
  // You can send any value at any time.
  // Please don't send more that 10 values per second.
  Blynk.virtualWrite(V2, millis() / 1000);
}

void setup()
{
  // Debug console
  Serial.begin(9600);

  Blynk.begin(auth);
  // You can also specify server:
  //Blynk.begin(auth, "blynk.cloud", 80);
  //Blynk.begin(auth, IPAddress(192,168,1,100), 8080);

  // Setup a function to be called every second
  timer.setInterval(1000L, myTimerEvent);
}

void loop()
{
  Blynk.run();
  timer.run();
  // You can inject your own code or combine it with other sketches.
  // Check other examples on how to communicate with Blynk. Remember
  // to avoid delay() function!
}

![blynk](https://user-images.githubusercontent.com/28201270/179423149-1120948e-0f67-4e2a-9908-3160b35be643.PNG)

This is with Ethernet2.h and BlynkSimpleEthernet2.h included. 

![ethernet2](h
![blynk_fail](https://user-images.githubusercontent.com/28201270/179423156-e7b0777f-5077-4c98-a9cf-920eb6dc08ff.PNG)
https://user-images.githubusercontent.com/28201270/179423153-c018a2fa-2826-4f31-8c8e-933ca8b7a464.PNG)
![ethernet](https://user-images.githubusercontent.com/28201270/179423552-cdb715df-26c6-41c8-9175-98cf6556b611.PNG)
 
This is with Ethernet.h and BlynkSimpleEthernet.h included.
![blynk_fail_ethernet](https://user-images.githubusercontent.com/28201270/179423698-5df214e2-ac8a-480f-b981-721ae69f8fb2.PNG)

**Comment by vshymanskyy** [comment]
Ethernet2 support is removed by Arduino. Please use an ordinary Ethernet library.
