### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-sketch-generator#12]
In case we will pass token in url we need to enable SSL.

Instruction is must have.

**Comment by vshymanskyy** [comment]
We can just enable SSL, and redirect http -> https by default.
Blynk-provided URLs should be always https

**Comment by doom369** [comment]
Enabling SSL requires certificates and script that will renew certs.

**Comment by vshymanskyy** [comment]
Now that I added auth-token, this gets higher priority.
