### ISSUE TITLE
Add Token field input

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-sketch-generator#2]
In case url has "token" field - sketch generator should put token instead of `YourAuthToken`

**Comment by vshymanskyy** [comment]
Do we need an actual text input filed, or adding an URL parameter would be OK?

**Comment by doom369** [comment]
Just URL param is ok.

**Comment by blynkkk** [comment]
Please add field as well. Just not make it mandatory

Having the field simplifies support. Please! 🙏
