### ISSUE TITLE
Problem with DHT11 example

### ISSUE THREAD

**Issue by shashidharybhat** [blynkkk/blynk-sketch-generator#28]
The simpleTimer library causes problems.

> In file included from C:\Users\Dell\Desktop\arduino projects\blynk_dht11\blynk_dht11.ino:46:0:
C:\Users\Dell\Documents\Arduino\libraries\SimpleTimer-master/SimpleTimer.h:39:14: error: 'function' in namespace 'std' does not name a template type
 typedef std::function<void(void)> timer_callback;
              ^
C:\Users\Dell\Documents\Arduino\libraries\SimpleTimer-master/SimpleTimer.h:58:29: error: 'timer_callback' has not been declared
     int setInterval(long d, timer_callback f);
                             ^
C:\Users\Dell\Documents\Arduino\libraries\SimpleTimer-master/SimpleTimer.h:61:28: error: 'timer_callback' has not been declared
     int setTimeout(long d, timer_callback f);
                            ^
C:\Users\Dell\Documents\Arduino\libraries\SimpleTimer-master/SimpleTimer.h:64:26: error: 'timer_callback' has not been declared
     int setTimer(long d, timer_callback f, int n);
                          ^
exit status 1
Error compiling for board Arduino/Genuino Uno.

>

**Comment by doom369** [comment]
@shashidharybhat please past URL you have used.

**Comment by shashidharybhat** [comment]
I didn't get your point.

**Comment by doom369** [comment]
Please show your skethc

**Comment by shashidharybhat** [comment]
> 
#define BLYNK_PRINT SwSerial


#include <SoftwareSerial.h>
SoftwareSerial SwSerial(10, 11); // RX, TX
    
#include <BlynkSimpleStream.h>
#include <SimpleTimer.h>
#include <DHT.h>

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "7aeec8512625490ba35cf28f0713480b";

#define DHTPIN 2          // What digital pin we're connected to

// Uncomment whatever type you're using!
#define DHTTYPE DHT11     // DHT 11
//#define DHTTYPE DHT22   // DHT 22, AM2302, AM2321
//#define DHTTYPE DHT21   // DHT 21, AM2301

DHT dht(DHTPIN, DHTTYPE);
SimpleTimer timer;

// This function sends Arduino's up time every second to Virtual Pin (5).
// In the app, Widget's reading frequency should be set to PUSH. This means
// that you define how often to send data to Blynk App.
void sendSensor()
{
  float h = dht.readHumidity();
  float t = dht.readTemperature(); // or dht.readTemperature(true) for Fahrenheit

  if (isnan(h) || isnan(t)) {
    SwSerial.println("Failed to read from DHT sensor!");
    return;
  }
  // You can send any value at any time.
  // Please don't send more that 10 values per second.
  Blynk.virtualWrite(V5, h);
  Blynk.virtualWrite(V6, t);
}

void setup()
{
  // Debug console
  SwSerial.begin(9600);

  // Blynk will work through Serial
  // Do not read or write this serial manually in your sketch
  Serial.begin(9600);
  Blynk.begin(Serial, auth);

  dht.begin();

  // Setup a function to be called every second
  timer.setInterval(1000L, sendSensor);
}

void loop()
{
  Blynk.run();
  timer.run(); // Initiates SimpleTimer
}

>

**Comment by shashidharybhat** [comment]
the same in the example browser

**Comment by doom369** [comment]
@shashidharybhat works fine for me. Try to remove and install Blynk library again. Also try to use latest Arduino IDE.

**Comment by shashidharybhat** [comment]
I have the latest IDE but I don't know to uninstall a library.

**Comment by doom369** [comment]
http://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment

**Comment by doom369** [comment]
How to install blynk library - https://github.com/blynkkk/blynk-library/releases

**Comment by shashidharybhat** [comment]
thanks  for your help and  time.

**Comment by doom369** [comment]
Did you solve the issue?

**Comment by shashidharybhat** [comment]
I'm trying it.

**Comment by shashidharybhat** [comment]
It worked thanks

**Comment by shashidharybhat** [comment]
Do you work for blynk

**Comment by doom369** [comment]
yes.
