### ISSUE TITLE
Connection type differs from app

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-sketch-generator#32]
Right now app has next Connection types : 

```
Ethernet,
WiFi,
USB,
GSM,
Bluetooth,
BLE
```

While in sketch generator present "Esp8266 WiFi". Can you fix that? 

For https://github.com/blynkkk/blynk-server/issues/500

**Comment by vshymanskyy** [comment]
No, as we discussed - connection types in apps are completely irrelevant

**Comment by doom369** [comment]
What is your proposal?

**Comment by vshymanskyy** [comment]
Need to define ALL hw connection on App side, or redesign the connection flow and get connection type from HW
