### ISSUE TITLE
Can't select Connection type for Raspberry

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-sketch-generator#33]

**Comment by vshymanskyy** [comment]
Why - this is not supported.

**Comment by doom369** [comment]
From user point of view it is a bit confusing.

**Comment by vshymanskyy** [comment]
For raspberry, it is System Default connection only which is WiFi or Ethernet (or any other, supported by linux).
This completely makes sense.

**Comment by vshymanskyy** [comment]
We can rename it like "Linux Internet" or something. Propose a new (less confusing) name.
