### ISSUE TITLE
Change Field name

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/blynk-sketch-generator#34]
Now:
Auth Token

![image](https://cloud.githubusercontent.com/assets/11541426/25101389/1cc33b24-2382-11e7-873a-b5e94d32c9f4.png)

Change to:
"Auth Token (optional)"

**Comment by blynkkk** [comment]
Or we need to to add a link  which would show where to get Auth Token. Many people ask in support

**Comment by vshymanskyy** [comment]
I think it is a bad idea to say it is optional (it is not - sketch won't work).

**Comment by doom369** [comment]
It is optional for sketch generator so it's fine.
