### ISSUE TITLE
#error Servo Library

### ISSUE THREAD

**Issue by vandaipham** [blynkkk/blynk-sketch-generator#36]
Anyone know how fix it??
#error "This library only supports boards with an AVR, SAM or SAMD processor."

**Comment by vshymanskyy** [comment]
As it says - default Servo library only supports these boards. It has nothing to do with Blynk, sorry.

**Comment by Ssy3** [comment]
1- Go to manage libraries
2- Search for esp32servo then install it
3- replace <Servo.h> in the code with <ESP32Servo.h>
