### ISSUE TITLE
Incorrect links in some ESP8266 as WiFi shield example sketches.

### ISSUE THREAD

**Issue by Gun-neR** [blynkkk/blynk-sketch-generator#38]
Arduino with ESP8266 as WiFi shield examples point to old (and empty) GitHub link when they should point to new Help Center page.

For example - https://examples.blynk.cc/?board=Arduino%20Uno&shield=ESP8266%20WiFi%20Shield&example=GettingStarted%2FBlynkBlink

Shows dead link that should be this instead:

http://help.blynk.cc/hardware-and-libraries/arduino/esp8266-with-at-firmware

Can't rely on many users actually searching for the proper info ;)

**Comment by doom369** [comment]
@Gun-neR thanks!

**Comment by vshymanskyy** [comment]
fixed
