### ISSUE TITLE
TimerLib missing in WidgetRTC in Raspberry Pi 3

### ISSUE THREAD

**Issue by ramsnavarro90** [blynkkk/blynk-sketch-generator#41]
Hello community. I am using Raspberry Pi 3 and am trying to implement an RTC Widget, but when save file and compile terminal prints an error. WidgetRTC includes TimerLib.h, but it does not find it. Please help me to solve this issue. Thanks.

In file included from main.cpp:13:0:
../src/WidgetRTC.h:16:21: fatal error: TimeLib.h: No such file or directory
 #include <TimeLib.h>
                     ^
compilation terminated.
Makefile:70: recipe for target 'main.o' failed
make: *** [main.o] Error 1

Part of code where this error happens...

#define BLYNK_PRINT   stdout
#include <BlynkApiWiringPi.h>
#include <BlynkSocket.h>
#include <BlynkOptionsParser.h>

static BlynkTransportSocket _blynkTransport;
BlynkSocket Blynk(_blynkTransport);

#include <BlynkWidgets.h>
#include <WidgetRTC.h>

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <wiringPi.h>
#include <wiringSerial.h>

**Comment by vshymanskyy** [comment]
We do not support some sketch combinations. This one is technically not feasible.
