### ISSUE TITLE
Problem in specifying server

### ISSUE THREAD

**Issue by kartik00013** [blynkkk/blynk-sketch-generator#42]
//Blynk.begin(auth, wifi, ssid, pass, IPAddress(192,168,1,100), 8442);
Arduino: 1.8.3 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\kartiksingh00013\Documents\Arduino\New_WIFI_code\New_WIFI_code.ino: In function 'void setup()':

New_WIFI_code:25: error: 'IPAddress' was not declared in this scope

   Blynk.begin(auth, wifi, ssid, pass, IPAddress(192,168,1,100),  8442);

                                                              ^

exit status 1
'IPAddress' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by vshymanskyy** [comment]
@kartik00013 which exactly sketch did you use? can you provide sketch link?

**Comment by vshymanskyy** [comment]
@kartik00013 for ESP8266, you can only specify it like ```Blynk.begin(auth, wifi, ssid, pass, "your ip or domain address", 8442);```

**Comment by kartik00013** [comment]
Thanks for your help. Can you also tell which IPAddres I need to define, if I am using local server

**Comment by vshymanskyy** [comment]
so that's IP of your local server
