### ISSUE TITLE
ESP32 ESP32 WiFi Email example crashes

### ISSUE THREAD

**Issue by whogarden** [blynkkk/blynk-sketch-generator#43]
With an ESP32 Dev-Kit and email example with no changes, when I press button on gpio 2 It crashes like this :
Button is pressed.
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU1)
Register dump:
PC      : 0x4008420d  PS      : 0x00060034  A0      : 0x80085833  A1      : 0x3ffc0590  
A2      : 0x3ffc1410  A3      : 0x00060021  A4      : 0x00060023  A5      : 0x00000020  
A6      : 0x00000020  A7      : 0x00060023  A8      : 0xb33f0001  A9      : 0xb33fffff  
A10     : 0x00060021  A11     : 0x00000000  A12     : 0x00060021  A13     : 0xffffffff  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000020  EXCCAUSE: 0x00000006  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x4008420d:0x3ffc0590 0x40085833:0x3ffc05b0 0x4008419e:0x3ffc05d0 0x4008636c:0x3ffc05f0 0x40082031:0x3ffc0600

CPU halted.

**Comment by whogarden** [comment]
And since that, I receive no email.
The first email when the esp boot is no more received in my mail box.
And also no email when I active the android app to send email auth token.
Nothing in email box spam.
Help me please.

**Comment by vshymanskyy** [comment]
please post your questions to https://community.blynk.cc
