### ISSUE TITLE
Blynk.virtialwrite throws exception

### ISSUE THREAD

**Issue by Tokn59** [blynkkk/blynk-sketch-generator#44]
Hello, I need some help please. Please find attached the code of my sketch. On line 202 :

202 Blynk.virtualWrite(V1, temp_c); // virtual pin 1 = Temp in C

when I remove this line's comments and thus try to write to Virtual Pin 1 I get an error message :

ets Jan 8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x0f
csum 0x0f
~ld

When I comment this line out the sketch ruins perfectly. Any idea what I am doing wrong ? I am running this on an ESP8266-12E board.

Sketch code attached as ZIP File
[ESPBlynkWunedrground.zip](https://github.com/blynkkk/blynk-sketch-generator/files/1242978/ESPBlynkWunedrground.zip)

**Comment by Tokn59** [comment]
Sorry now with correct Sketch Code attached, please ignore previous one.
[ESP8266BlynkWundergroundError.zip](https://github.com/blynkkk/blynk-sketch-generator/files/1243204/ESP8266BlynkWundergroundError.zip)

**Comment by vshymanskyy** [comment]
Please post your questions to https://community.blynk.cc
