### ISSUE TITLE
Not connecting via BLE (android, ios)

### ISSUE THREAD

**Issue by yaboiiia** [blynkkk/blynk-sketch-generator#45]
arduino 101 (powered through the usb port of computor)
samsung s8

Using example code "arduino_101_ble"

trying to control a led using ~9 port but cant even connect to the board.

All goes well until I try to connect through my device (galaxy s8). The app tells me "failed to connect" or hangs on "connecting".

Bluetooth on the device is on but is not connected to the Arduino101 (displayed as "blynk") 

The serial monitor:

[2277] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v0.4.8 on Arduino 101

Waiting for connections...
[30959] Disconnected

Its probably just a silly mistake I've made but holy moly I've been trying to do this simple task for the entire day.

also if anyone knows whether or not its possible to control an two esc's via blynk for a tank

if u could help it will help heaps

**Comment by vshymanskyy** [comment]
This is known, please search our forum

**Comment by yaboiiia** [comment]
legendary, fast asf thankyou
