### ISSUE TITLE
Example "Push Notification Button" uses Pin 2 on MKR1000 but it hasn't interrupt

### ISSUE THREAD

**Issue by giufini** [blynkkk/blynk-sketch-generator#47]
The code of the example "Push Notification Button" generated for an Arduino/Genuino MKR1000 board, using the built-in Arduino WiFi Shield 101, uses Pin 2 to connect an external button, anyway Pin 2 has no interrupt so it must be used a different pin (I used Pin 4).

**Comment by vshymanskyy** [comment]
This is just an example - so use proper pins for your board.
