### ISSUE TITLE
Blynk DHT11 sketch with Wemos D1 mini

### ISSUE THREAD

**Issue by Hansta98** [blynkkk/blynk-sketch-generator#48]
If you have the same problem I had, to read temperature with the DHT11 and show the data in Blynk app, try this out? The most important difference between the original sketch from Blynk`s sketch generator and the sketch which works with my Wemos lies in the 8th line. The output of Wemos D1 mini is not called for example 2, it is called D2. Now the sketch look like this one
 #define BLYNK_PRINT Serial

#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <DHT.h>

char auth[] = "8043f9178b59......8565743f3c2ad";
char ssid[] = "SSID";
char pass[] = "Passwort";

#define DHTPIN D2                                         //The DataPin is conected on Wemos D1 with D2
#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE, 30);
BlynkTimer timer;

void sendSensor()
{
  float h = dht.readHumidity();
  float t = dht.readTemperature();                        // or dht.readTemperature(true) for Fahrenheit
  Serial.print(" Luftfeuchtigkeit in Grad:");             //Humidity (Value in %)
  Serial.print(h);
  Serial.println(" % ");
  Serial.print(" Temperatur:");                           //Temperature (Value in Grad Celsius)
  Serial.print(t);
  Serial.println(" *C ");
  
  if (isnan(h) || isnan(t)) {
    Serial.println("Problem!");
    return;
  }
  Blynk.virtualWrite(V5, h);
  Blynk.virtualWrite(V6, t);
}

void setup()
{
  // Debug console
  Serial.begin(9600);
  Blynk.begin(auth, ssid, pass);
  dht.begin();
  timer.setInterval(2000L, sendSensor);                 //Every 2s Blynk update the measuring result
}

void loop()
{
  Blynk.run();
  timer.run();
}

**Comment by vshymanskyy** [comment]
Thanks.
