### ISSUE TITLE
BlynkSimpleEsp32.h:   No such file or directory

### ISSUE THREAD

**Issue by csmcvea** [blynkkk/blynk-sketch-generator#52]
I tried to compile my first project and 
I have the error BlynkSimpleEsp32.h:   No such file or directory
I Have a known good working ESP32 that I have used for connection to WiFi with success.
Please help this newbie.  Thank you.

Arduino: 1.8.5 (Mac OS X), Board: "Adafruit ESP32 Feather, 80MHz, 921600, Info"
/Users/csmcvea/Documents/Arduino/libraries/Blynk_Release_v0/libraries/GarageDoorOpener/GarageDoorOpener.ino:40:30: fatal error: BlynkSimpleEsp32.h: No such file or directory
compilation terminated.
exit status 1
`/*************************************************************
  Download latest Blynk library here:
    https://github.com/blynkkk/blynk-library/releases/latest

  Blynk is a platform with iOS and Android apps to control
  Arduino, Raspberry Pi and the likes over the Internet.
  You can easily build graphic interfaces for all your
  projects by simply dragging and dropping widgets.

    Downloads, docs, tutorials: http://www.blynk.cc
    Sketch generator:           http://examples.blynk.cc
    Blynk community:            http://community.blynk.cc
    Follow us:                  http://www.fb.com/blynkapp
                                http://twitter.com/blynk_app

  Blynk library is licensed under MIT license
  This example code is in public domain.

 *************************************************************

  You’ll need:
   - Blynk App (download from AppStore or Google Play)
   - ESP32 board
   - Decide how to connect to Blynk
     (USB, Ethernet, Wi-Fi, Bluetooth, ...)

  There is a bunch of great example sketches included to show you how to get
  started. Think of them as LEGO bricks  and combine them as you wish.
  For example, take the Ethernet Shield sketch and combine it with the
  Servo example, or choose a USB sketch and add a code from SendData
  example.
 *************************************************************/

/* Comment this out to disable prints and save space */
#define BLYNK_PRINT Serial

#include <WiFi.h>
#include <WiFiClient.h>
#include <BlynkSimpleEsp32.h>

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "060xxxxxxxxxxxxxxxxxxxxxxxxxxxxf062";

// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "my SSID here";
char pass[] = "my PASS here";

void setup()
{
  // Debug console
  Serial.begin(9600);

  Blynk.begin(auth, ssid, pass);
  // You can also specify server:
  //Blynk.begin(auth, ssid, pass, "blynk-cloud.com", 8442);
  //Blynk.begin(auth, ssid, pass, IPAddress(192,168,1,100), 8442);
}

void loop()
{
  Blynk.run();
  // You can inject your own code or combine it with other sketches.
  // Check other examples on how to communicate with Blynk. Remember
  // to avoid delay() function!
}

My directory structure:
`.DS_Store
libraries
tools

/Users/csmcvea/Documents/Arduino/libraries/Blynk_Release_v0/libraries:
.DS_Store
Blynk
BlynkESP8266_Lib
GarageDoorOpener
Time
TinyGSM

/Users/csmcvea/Documents/Arduino/libraries/Blynk_Release_v0/libraries/Blynk:
.DS_Store
LICENSE
Makefile
README.md
examples
keywords.txt
library.json
library.properties
linux
scripts
src
tests

/Users/csmcvea/Documents/Arduino/libraries/Blynk_Release_v0/libraries/Blynk/examples:
.DS_Store
Boards_Bluetooth
Boards_Ethernet
Boards_GSM
Boards_USB_Serial
Boards_WiFi
Boards_With_HTTP_API
Export_Demo

^G Get Help    ^O WriteOut    ^R Read File   ^Y Prev Page   ^K Cut Text    ^C Cur Pos
`

**Comment by vshymanskyy** [comment]
please consult our community forum for such questions: https://community.blynk.cc/
