### ISSUE TITLE
BlynkSimpleEsp8266.h does not exist

### ISSUE THREAD

**Issue by P-A-B-L-O** [blynkkk/blynk-sketch-generator#55]
I'm using NodeMCU board and "Blynk Blink" example. Arduino IDE is showing statement: 

C:\Users\PaweĹ‚\AppData\Local\Temp\arduino_modified_sketch_384200\sketch_jan19a.ino:39:32: fatal error: BlynkSimpleEsp8266.h: No such file or directory

I've downloaded and unziped Blynk library.

**Comment by TillW99** [comment]
I have the same problem, an Arduino Nano with esp2866. The code from the Website generated, but it print this error every time! And I have searched after the file: it exists!

**Comment by hroc65** [comment]
Blynk Blink example won't compile.Keeps getting Error.

**Comment by vshymanskyy** [comment]
please consult our community forum for such questions: https://community.blynk.cc/
