### ISSUE TITLE
Raspberry Pi > Push data on request > fatal error: BlynkSocket.h: No such file or directory

### ISSUE THREAD

**Issue by elongo** [blynkkk/blynk-sketch-generator#56]
When compiling the example sketch found here for RPi > Push data on request the following errors are returned. Is there any way to fix these dependencies issue?:

fatal error: BlynkApiLinux.h: No such file or directory
fatal error: BlynkSocket.h: No such file or directory

**Comment by vshymanskyy** [comment]
please consult our community forum for such questions: https://community.blynk.cc/
