### ISSUE TITLE
AdvancedTimeInput sample dont run Arduino IDE

### ISSUE THREAD

**Issue by alessandrocarlom** [blynkkk/blynk-sketch-generator#63]
I copied the AdvancedTimeInput sample from https://examples.blynk.cc/?board=ESP8266&shield=ESP8266%20WiFi&example=Widgets%2FTimeInput%2FAdvancedTimeInput but when I try to run I get: "exit status 1
'TimeInputParam' was not declared in this scope "of the Arduino IDE.

Windows 7, Arduino IDE 1.8.2, Blynk library 0.5.2

Complete error : 
C:\Users\alessandro\Documents\Arduino\ESP8266_Teste_Blynk_Advanced_Time_Input\ESP8266_Teste_Blynk_Advanced_Time_Input.ino: In function 'void BlynkWidgetWrite1(BlynkReq&, const BlynkParam&)':

ESP8266_Teste_Blynk_Advanced_Time_Input:42: error: 'TimeInputParam' was not declared in this scope

   TimeInputParam t(param);

   ^

ESP8266_Teste_Blynk_Advanced_Time_Input:42: error: expected ';' before 't'

   TimeInputParam t(param);

                  ^

ESP8266_Teste_Blynk_Advanced_Time_Input:46: error: 't' was not declared in this scope

   if (t.hasStartTime())

       ^

ESP8266_Teste_Blynk_Advanced_Time_Input:68: error: 't' was not declared in this scope

   if (t.hasStopTime())

       ^

ESP8266_Teste_Blynk_Advanced_Time_Input:91: error: 't' was not declared in this scope

   Serial.println(String("Time zone: ") + t.getTZ());

                                          ^

Multiple libraries were found for "BlynkSimpleEsp8266.h"
Used: C: \ Users \ alessandro \ Documents \ Arduino \ libraries \ Cayenne
Not used: C: \ Users \ alessandro \ Documents \ Arduino \ libraries \ Blynk
Not used: C: \ Users \ alessandro \ Documents \ Arduino \ libraries \ Blynk
Not used: C: \ Users \ alessandro \ Documents \ Arduino \ libraries \ Blynk
Not used: C: \ Users \ alessandro \ Documents \ Arduino \ libraries \ Blynk

exit status 1
'TimeInputParam' was not declared in this scope

**Comment by vshymanskyy** [comment]
I just rechecked and it works fine.
Please consult our community forum for such questions: https://community.blynk.cc/
