### ISSUE TITLE
Default port for ESP as shield is too high for recommended use. 

### ISSUE THREAD

**Issue by Gun-neR** [blynkkk/blynk-sketch-generator#68]
As commented in the forum here...

https://community.blynk.cc/t/sketch-builder-combo-arduino-uno-esp-as-shield/29126

// Your ESP8266 baud rate:
#define ESP8266_BAUD 115200

Recommended stable BAUD for softserial in Blynk usage is 9600

**Comment by vshymanskyy** [comment]
@Gun-neR changed to 38400
