### ISSUE TITLE
Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"  C:\Users\OrionSirius\Documents\Arduino\sketch_oct17a\sketch_oct17a.ino:40:17: fatal error: DHT.h: No such file or directory   #include <DHT.h>                   ^  compilation terminated.  exit status 1 Error compiling for board NodeMCU 1.0 (ESP-12E Module).  This report would have more information with "Show verbose output during compilation" option enabled in File -> Preferences.

### ISSUE THREAD

**Issue by DALLASPI** [blynkkk/blynk-sketch-generator#69]
Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\OrionSirius\Documents\Arduino\sketch_oct17a\sketch_oct17a.ino:40:17: fatal error: DHT.h: No such file or directory

 #include <DHT.h>

                 ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by vshymanskyy** [comment]
Please use community forum https://community.blynk.cc/ for such questions.
