### ISSUE TITLE
I don't see any output with "getData" Example 

### ISSUE THREAD

**Issue by ollio** [blynkkk/blynk-sketch-generator#70]
I have setup NodeMCU and installed the source code. At my mobile phone I can see that I'm connected and at the serial terminal I see the welcome screen. 
Last line is "[1229] Ready (ping: 26ms)."

Now I have testet around but the "V1 Slider value is" never happens.

**Comment by vshymanskyy** [comment]
Please use community forum https://community.blynk.cc/ for such questions.
