### ISSUE TITLE
Arduino 101 ble conecction problem.

### ISSUE THREAD

**Issue by Maurice-Bakker** [blynkkk/blynk-sketch-generator#71]

**Comment by Maurice-Bakker** [comment]
Hello,

I Have an Arduino 101 in my garage to controle the lights and the temperature inside the garage. 
I have had it working for 6months now. 
The BLE connection with my phone always worked great. 

from the last month my phone can't connect to the board. the blynk app says:

Can't connect. device is not connected. Please check if the Auth Token is correct.

I've already checked the authtoken it is good. 
The board is running on version 1.0.7.  the latest (2.0.2.) has never worked for me.
I have the latest blynk library installed: Blynk_Release_v0.5.4

this is de code i use for the bluetooth connection:

#define BLYNK_PRINT Serial
#include <BlynkSimpleCurieBLE.h>
#include <CurieBLE.h>

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "33ea2ffbf2bb464cb5ddfb49f1f25ab9";

BLEPeripheral  blePeripheral;

void setup()
{
  // Debug console
  Serial.begin(9600);

  delay(1000);

  blePeripheral.setLocalName("Garage");
  blePeripheral.setDeviceName("Garage");
  blePeripheral.setAppearance(384);

  Blynk.begin(blePeripheral, auth);

  blePeripheral.begin();

  Serial.println("Waiting for connections...");
}

void loop()
{
  blePeripheral.poll();
  Blynk.run();
  
}

Can someone help me with the BLE connection?

**Comment by Maurice-Bakker** [comment]
can anybody help me please?

**Comment by PolinaRubinova** [comment]
получилось решить?

**Comment by vshymanskyy** [comment]
BLE is currently not supported in Blynk 2.0
