### ISSUE TITLE
can anybody tell me what could be the solution to this error

### ISSUE THREAD

**Issue by gunesana** [blynkkk/blynk-sketch-generator#73]
Arduino: 1.8.7 (Windows 7), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, Enabled, 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Multiple libraries were found for "BlynkSimpleEsp8266.h"
 Used: C:\Users\Laishram\Documents\Arduino\libraries\Blynk
In file included from C:\Users\Laishram\Documents\Arduino\libraries\DHT-sensor-library-master\DHT_U.cpp:22:0:

 Not used: C:\Program Files (x86)\Arduino\libraries\Blynk
 Not used: C:\Program Files (x86)\Arduino\libraries\Blynk
 Not used: C:\Program Files (x86)\Arduino\libraries\Blynk
C:\Users\Laishram\Documents\Arduino\libraries\DHT-sensor-library-master\DHT_U.h:25:29: fatal error: Adafruit_Sensor.h: No such file or directory

 Not used: C:\Program Files (x86)\Arduino\libraries\Blynk
 #include <Adafruit_Sensor.h>

                             ^

compilation terminated.

Multiple libraries were found for "DHT.h"
 Used: C:\Users\Laishram\Documents\Arduino\libraries\DHT-sensor-library-master
 Not used: C:\Program Files (x86)\Arduino\libraries\DHT-sensor-library-master
exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc/
