### ISSUE TITLE
Blynk Mega 2560 + ESP8266 wifi shield 'IPAddress' was not declared in this scope

### ISSUE THREAD

**Issue by kuchsk** [blynkkk/blynk-sketch-generator#77]
When uncomment - Blynk.begin(auth, wifi, ssid, pass, IPAddress(192,168,1,100), 8080);
error appears - 'IPAddress' was not declared in this scope 

https://examples.blynk.cc/?board=Arduino%20Mega%202560&shield=ESP8266%20WiFi%20Shield&example=GettingStarted%2FBlynkBlink

and i can't declare this in the scetch
IPAddress local_IP(192, 168, 1, 11);
IPAddress gateway(192, 168, 1, 1);
IPAddress subnet(255, 255, 255, 0);
IPAddress primaryDNS(8, 8, 8, 8);
IPAddress secondaryDNS(8, 8, 4, 4);

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc/
