### ISSUE TITLE
error getting from blynk library 

### ISSUE THREAD

**Issue by jaswinder247** [blynkkk/blynk-sketch-generator#81]
In file included from C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:16,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkApiArduino.h:14,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/Adapters/BlynkSerial.h:18,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkSimpleSerialBLE.h:23,
                 from sketch_feb24b.ino:7:
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkParam.h:110: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkParam.h:115: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkParam.h:116: error: ISO C++ does not include variadic templates
In file included from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkApiArduino.h:14,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/Adapters/BlynkSerial.h:18,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkSimpleSerialBLE.h:23,
                 from sketch_feb24b.ino:7:
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:75: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:76: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:124: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:125: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:138: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:139: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:227: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkApi.h:228: error: ISO C++ does not include variadic templates
In file included from C:\Program Files (x86)\Arduino\libraries\Blynk\src/WidgetLED.h:13,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkWidgets.h:10,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkSimpleSerialBLE.h:28,
                 from sketch_feb24b.ino:7:
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:25: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:26: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:30: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:31: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:35: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:36: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:40: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/Blynk/BlynkWidgetBase.h:41: error: ISO C++ does not include variadic templates
In file included from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkWidgets.h:13,
                 from C:\Program Files (x86)\Arduino\libraries\Blynk\src/BlynkSimpleSerialBLE.h:28,
                 from sketch_feb24b.ino:7:
C:\Program Files (x86)\Arduino\libraries\Blynk\src/WidgetBridge.h:55: error: ISO C++ does not include variadic templates
C:\Program Files (x86)\Arduino\libraries\Blynk\src/WidgetBridge.h:56: error: ISO C++ does not include variadic templates
sketch_feb24b.ino: In function 'void loop()':
sketch_feb24b:29: error: expected `}' at end of input

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc
