### ISSUE TITLE
how to remove a mistake

### ISSUE THREAD

**Issue by GregoryShapovalov** [blynkkk/blynk-sketch-generator#88]
Arduino: 1.8.9 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Pavel\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Pavel\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Pavel\Documents\Arduino\libraries -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=80,UploadSpeed=115200,FlashSize=4M3M -ide-version=10809 -build-path C:\Users\Pavel\AppData\Local\Temp\arduino_build_868285 -warnings=none -build-cache C:\Users\Pavel\AppData\Local\Temp\arduino_cache_336339 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.xtensa-lx106-elf-gcc-1.20.0-26-gb404fb9-2.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.esptool.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.9 -prefs=runtime.tools.esptool-0.4.9.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.9 -prefs=runtime.tools.mkspiffs.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\mkspiffs\0.1.2 -prefs=runtime.tools.mkspiffs-0.1.2.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\mkspiffs\0.1.2 -verbose C:\Users\Pavel\Documents\Arduino\1\1.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Pavel\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Pavel\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Pavel\Documents\Arduino\libraries -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=80,UploadSpeed=115200,FlashSize=4M3M -ide-version=10809 -build-path C:\Users\Pavel\AppData\Local\Temp\arduino_build_868285 -warnings=none -build-cache C:\Users\Pavel\AppData\Local\Temp\arduino_cache_336339 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.xtensa-lx106-elf-gcc-1.20.0-26-gb404fb9-2.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.esptool.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.9 -prefs=runtime.tools.esptool-0.4.9.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.9 -prefs=runtime.tools.mkspiffs.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\mkspiffs\0.1.2 -prefs=runtime.tools.mkspiffs-0.1.2.path=C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\tools\mkspiffs\0.1.2 -verbose C:\Users\Pavel\Documents\Arduino\1\1.ino
Using board 'nodemcuv2' from platform in folder: C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0
Using core 'esp8266' from platform in folder: C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0
Detecting libraries used...
"C:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0/tools/sdk/include" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0/tools/sdk/lwip/include" "-IC:\\Users\\Pavel\\AppData\\Local\\Temp\\arduino_build_868285/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DARDUINO=10809 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266 "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\cores\\esp8266" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\variants\\nodemcu" "C:\\Users\\Pavel\\AppData\\Local\\Temp\\arduino_build_868285\\sketch\\1.ino.cpp" -o nul
"C:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0/tools/sdk/include" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0/tools/sdk/lwip/include" "-IC:\\Users\\Pavel\\AppData\\Local\\Temp\\arduino_build_868285/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DARDUINO=10809 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266 "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\cores\\esp8266" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\variants\\nodemcu" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\libraries\\ESP8266WiFi\\src" "C:\\Users\\Pavel\\AppData\\Local\\Temp\\arduino_build_868285\\sketch\\1.ino.cpp" -o nul
"C:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0/tools/sdk/include" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0/tools/sdk/lwip/include" "-IC:\\Users\\Pavel\\AppData\\Local\\Temp\\arduino_build_868285/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DARDUINO=10809 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266 "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\cores\\esp8266" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\variants\\nodemcu" "-IC:\\Users\\Pavel\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.3.0\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\Pavel\\Documents\\Arduino\\libraries\\Blynk\\src" "C:\\Users\\Pavel\\AppData\\Local\\Temp\\arduino_build_868285\\sketch\\1.ino.cpp" -o nul
In file included from C:\Users\Pavel\Documents\Arduino\1\1.ino:39:0:

C:\Users\Pavel\Documents\Arduino\libraries\Blynk\src/BlynkSimpleEsp8266_SSL.h:18:21: fatal error: version.h: No such file or directory

 #include <version.h>

                     ^

compilation terminated.

Using library ESP8266WiFi at version 1.0 in folder: C:\Users\Pavel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi 
Using library Blynk at version 0.6.1 in folder: C:\Users\Pavel\Documents\Arduino\libraries\Blynk 
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by vshymanskyy** [comment]
Please use https://community.blynk.cc/
