### ISSUE TITLE
Sync Physical Button - Poor GPIO choice

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/blynk-sketch-generator#89]
The Sync Physical Button sketch in the Sketch Builder uses GPIO pins 7 & 8
```
// Set your LED and physical button pins here
const int ledPin = 7;
const int btnPin = 8;
```
These are reserved pins for the ESP8266 and when the code is uploaded the device will will connect to WiFi and Blynk, then do a WDT reset with ```cause:4, boot mode:(3,6)``` and constantly loop in this way.

Please change the pins to ones that are appropriate for both Arduino and ESP8266, or add a comment to the sketch saying that different pins need to be used for the ESP8266.

Thanks.

**Comment by vshymanskyy** [comment]
changed to 
```
const int ledPin = 13;
const int btnPin = 12;
```
