### ISSUE TITLE
TinyURL for USB How-To is broken

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/blynk-sketch-generator#92]
Selecting an Arduino Uno board with connection type of Serial or USB includes this section of code:
```
  =>
  =>          USB HOWTO: http://tiny.cc/BlynkUSB
  =>
```
THe TinyURL of http://tiny.cc/BlynkUSB now takes the user to a website advertising tyres (or tires for our American cousins who like to masacre the Queen's English).

Pete.

**Comment by doom369** [comment]
@Peterkn2001 thanks! Removed for now.
