### ISSUE TITLE
SerialBLE Not Declared Error with BLE examples

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/blynk-sketch-generator#93]
Hi guys,
Two issues here:
1) with Arduino UNO and HM10/HC08
The SoftwareSerial port is declared as SwSerial:
```
SoftwareSerial SwSerial(10, 11); // RX, TX
```
but void setup() references it as SerialBLE:
```
  SerialBLE.begin(9600);
  Blynk.begin(SerialBLE, auth);
```
_________________________________________________________

2) with Arduino Mega and HM10/HC08
One of the Mega's extra 3 serial hardware ports should be used, so this:
```
  SerialBLE.begin(9600);
  Blynk.begin(SerialBLE, auth);
```
could be modified to directly reference Serial1, Serial2 or Serial3 instead of SerialBLE, or one of these ports could be given the alias of SerialBLE before void setup() executes.

Community topic on this issue here:
https://community.blynk.cc/t/arduino-mega-not-connecting-to-ble-serialble-was-not-declared-in-this-scope/45188

I'm guessing that more sketches may be affected, but I've not checked. Probably a result of a recent change?

Pete

**Comment by dmsergeevich63** [comment]
I have the same error on arduino nano with the HC-05 Bluetooth module and tried to solve it as you described https://community.blynk.cc/t/arduino-mega-not-connecting-to-ble-serialble-was-not -declared-in-this-scope / 45188
But I still could not get any result, here is my code:
```
#define BLYNK_PRINT Serial


#include <SoftwareSerial.h>
//SoftwareSerial SwSerial(10, 11); // RX, TX

#include <BlynkSimpleSerialBLE.h>
SoftwareSerial SerialBLE(10, 11); // RX, TX //D6, D7


// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "xxx";

BlynkTimer timer;

// This function sends Arduino's up time every second to Virtual Pin (5).
// In the app, Widget's reading frequency should be set to PUSH. This means
// that you define how often to send data to Blynk App.
void myTimerEvent()
{
  // You can send any value at any time.
  // Please don't send more that 10 values per second.
  Blynk.virtualWrite(V5, millis() / 1000);
}
void setup()
{
  // Debug console
  Serial.begin(2400);

    SerialBLE.begin(2400);
  Blynk.begin(SerialBLE, auth);
  timer.setInterval(1000L, myTimerEvent);
}

void loop()
{
  Blynk.run();
  timer.run();
}
```

**Comment by Peterkn2001** [comment]
@dmsergeevich63 the code you posted above compiled without any errors for me.
What compilation errors are you seeing?

Pete.

**Comment by dmsergeevich63** [comment]
@Peterkn2001  I also have no errors, but blynk on the smartphone does not respond in any way

**Comment by Peterkn2001** [comment]
Okay, this GitHub issue it to inform the Blynk developers that there are compilation errors with some of the sketchbuilder BLE examples because of the way that the Serial/SoftwareSerial port names have been defined.
You encountered this problem when using the Arduino Nano and HC05/HC06 example, and you resolved the problem by changing the SoftwareSerial port name from SwSerial to SerialBLE. The problems you now have are unrelated to this GitHub issue, so this is not the place to discuss and attempt to resolve them.
Please create a new "Need help with my project" topic on the Blynk Community forum and provide all of the relevant information, and the community members will attempt to help you with your problem.

Pete.

**Comment by GeorgeMpouk** [comment]
SoftwareSerial SerialBLE(10, 11); // RX, TX 
This is the solution for serialBLE not declared, its from another reported issue here https://github.com/blynkkk/blynk-sketch-generator/issues/95#issuecomment-648577276

**Comment by vshymanskyy** [comment]
BLE is currently not supported in Blynk 2.0
