### ISSUE TITLE
Error de compilación Blynk + Arduino uno y HC-08

### ISSUE THREAD

**Issue by fabianfama** [blynkkk/blynk-sketch-generator#97]
Estoy intentando compilar el codigo que se genera en forma automatica en Blynk para un ejemplo que reune la placa Arduino uno con un modulo BLE HC-08 y recibo un error de compilacion.......a que se debe???

El codigo es:

* Comment this out to disable prints and save space */
#define BLYNK_PRINT Serial

#include <SoftwareSerial.h>
SoftwareSerial SwSerial(10, 11); // RX, TX

#include <BlynkSimpleSerialBLE.h>
#include <Servo.h>

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "YourAuthToken";

Servo servo;

BLYNK_WRITE(V3)
{
  servo.write(param.asInt());
}

void setup()
{
  // Debug console
  Serial.begin(9600);

  SerialBLE.begin(9600);
  Blynk.begin(SerialBLE, auth);

  Serial.println("Waiting for connections...");

  servo.attach(9);
}

void loop()
{
  Blynk.run();
}

El error es el siguiente:  

**C**:\Users\fabia\Documents\Arduino\Blynk_Bluetooth-Servo\Blynk_Bluetooth-Servo.ino: In function 'void setup()':

Blynk_Bluetooth-Servo:27:3: error: 'SerialBLE' was not declared in this scope

   SerialBLE.begin(9600);

   ^~~~~~~~~

C:\Users\fabia\Documents\Arduino\Blynk_Bluetooth-Servo\Blynk_Bluetooth-Servo.ino:27:3: note: suggested alternative: 'Serial'

   SerialBLE.begin(9600);

   ^~~~~~~~~

   Serial

Usando librería SoftwareSerial con versión 1.0 en la carpeta: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.42.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\SoftwareSerial 

Usando librería Blynk con versión 0.6.1 en la carpeta: C:\Users\fabia\Documents\Arduino\libraries\Blynk 

Usando librería Servo con versión 1.1.6 en la carpeta: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.42.0_x86__mdqgnx93n4wtt\libraries\Servo 

exit status 1

'SerialBLE' was not declared in this scope****

Desde ya muchas gracias

**Comment by vshymanskyy** [comment]
BLE is currently not supported in Blynk 2.0
